Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using ProstoAndVkusno.Data.Interfaces;
using ProstoAndVkusno.Data.Models;
using ProstoAndVkusno.DBContext;
using System.Diagnostics.Eventing.Reader;

namespace ProstoAndVkusno.Controllers
{
    public class OrderController : Controller
    {
        // Внедрение зависимостей для работы с заказами и корзиной
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        // Конструктор для инициализации зависимостей
        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        // Страница оформления заказа
        public IActionResult Checkout()
        {
            return View();
        }

        // Обработка формы оформления заказа
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.ListShopItems = shopCart.GetShopItems();

            // Проверка, есть ли товары в корзине
            if (shopCart.ListShopItems.Count == 0)
            {
                TempData["ErrorMessage"] = "В корзине должны быть товары!";
                return RedirectToAction("List", "Products");
            }

            // Проверка валидации модели
            if (ModelState.IsValid)
            {
                allOrders.createOrder(order);
                shopCart.ClearCart();
                return RedirectToAction("Complete");
            }
            else
            {
                return View(order);
            }
        }

        // Страница подтверждения заказа
        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using ProstoAndVkusno.Data.Interfaces;
using ProstoAndVkusno.Data.Models;
using ProstoAndVkusno.Data.Repository;
using ProstoAndVkusno.ViewModels;

namespace ProstoAndVkusno.Controllers
{
    public class ShopCartController : Controller
    {
        // Внедрение зависимостей для работы с товарами и корзиной
        private readonly IAllProducts _productRepository;
        private readonly ShopCart _shopCart;

        // Конструктор для инициализации зависимостей
        public ShopCartController(IAllProducts productRepository, ShopCart shopCart)
        {
            _productRepository = productRepository;
            _shopCart = shopCart;
        }

        // Страница корзины
        public ViewResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;

            // Создание модели представления для передачи данных в представление
            var obj = new ShopCartVM
            {
                shopCart = _shopCart
            };

            return View(obj);
        }

        // Добавление товара в корзину
        [HttpPost]
        public IActionResult addToCart(int id)
        {
            // Поиск товара по ID
            var item = _productRepository.GetProducts.FirstOrDefault(i => i.ID == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
                _shopCart.ListShopItems = _shopCart.GetShopItems();
                var cartVM = new ShopCartVM { shopCart = _shopCart };

                return PartialView("_ShopCartPartial", cartVM);
            }

            return Json(new { success = false, message = "Товар не найден" });
        }

        // Удаление товара из корзины
        public RedirectToActionResult RemoveFromCart(int itemId)
        {
            _shopCart.RemoveFromCart(itemId);

            return RedirectToAction("Index");
        }
    }
}

Views/ShopCart/Index.cshtml
@model ShopCartVM

<div class="container">
    <div id="cart-container">
        <ul>
            @if (Model.shopCart.ListShopItems.Count == 0)
            {
                <li>Корзина пуста</li>
            }
            else
            {
                @foreach (var el in Model.shopCart.ListShopItems)
                {
                    <li>
                        @el.product.Name - @el.price руб.
                        <a asp-controller="ShopCart" asp-action="RemoveFromCart" asp-route-itemId="@el.ID" class="btn btn-danger">Удалить</a>
                    </li>
                }
            }
        </ul>
    </div>

    <hr />
    <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>

Views/ShopCart/_ShopCartPartial.cshtml
@model ShopCartVM

<ul>
    @if (Model.shopCart.ListShopItems.Count == 0)
    {
        <li>Корзина пуста</li>
    }
    else
    {
        @foreach (var el in Model.shopCart.ListShopItems)
        {
            <li>
                @el.product.Name - @el.price руб.
                <a href="#" class="remove-from-cart" data-item-id="@el.ID">Удалить</a>
            </li>
        }
    }
</ul>